export interface TeamMember {
  name: string;
  role: string;
  image: string;
  linkedin?: string;
  instagram?: string;
  github?: string;
  note?: string;
}

export const EC_MEMBERS: TeamMember[] = [
    {
    name: "Samaksh Gupta",
    image: "https://images.prismic.io/ieeemuj/ZnJjw5m069VX13S1_IMG-20240405-WA0024~2-SamakshGupta.jpg?auto=format,compress",
    role: "Chairperson",
    linkedin: "https://www.linkedin.com/in/samakshgupta04",
    github: "https://github.com/AwesomeSam9523/",
    instagram: "https://www.instagram.com/samaksh.gupta04?igsh=c252dTcwNjZldWRp",
    note: "A leader who never needed to be loud to be respected ✨ You led with calmness, clarity, and a quiet kind of confidence that made everything feel manageable. A tech genius, yes—but also someone so soft, approachable, and genuinely kind. You showed us that the best leaders are the ones who make others feel capable 🫶🏻",
  },
  {
    name: "Tamanna Yadav",
    image: "https://images.prismic.io/ieeemuj/ZnHEBZm069VX12wA_IMG_20240617_153104-TamannaYadav.jpg?auto=format,compress",
    role: "Vice Chairperson",
    linkedin: "https://www.linkedin.com/in/tamanna-yadav-4251a6234",
    github: "",
    instagram: "https://www.instagram.com/tamanna.yadav_?igsh=MWl3Ym16bDMyOHBtZg==",
    note: "You are that perfect mix of chaos, strength, and warmth ☕✨ The one who could handle everything and still be up for chai and long conversations. You created a space where people could laugh, vent, and just exist freely. Strong yet so comforting, fun yet so grounding—you’re truly one of a kind 💅🏻",
  },
{
  name: "Salaj Singh Bisht",
  image: "https://images.prismic.io/ieeemuj/ZnHLL5m069VX12yn_IMG_20240416_161408-SalajBisht.jpg?auto=format,compress",
  role: "General Secretary",
  linkedin: "https://www.linkedin.com/in/salaj-singh-bisht-837899248",
  github: "",
  instagram: "https://instagram.com/_.bishttt._",
  note: "You are the thread that quietly holds everything and everyone together 🫶🏻 Being Gen Sec was just your role, but being everyone’s favourite—that’s who you are. You made people feel seen, valued, and connected, without ever trying too hard. Because of you, this wasn’t just a chapter—it was a home. And that feeling is something we’ll never forget 🥹",
},
{
  name: "Aryan Verma",
  image: "https://images.prismic.io/ieeemuj/aENAFrh8WN-LVx3f_IMG_0788-AryanVerma.jpeg?auto=format,compress",
  role: "Managing Director",
  linkedin: "https://www.linkedin.com/in/aryannnnverma",
  github: "https://github.com/aryannverse",
  instagram: "https://www.instagram.com/aryannverse",
  note: "You brought magic into everything you touched ✨ Like our very own Doraemon, always ready with creativity that made things feel alive. But what made you special wasn’t just your editing—it was how fun, kind, and easy you are to be around. With you, everything felt lighter, cooler, and a little more special 🫶🏻",
},
{
  name: "Vinayak Jajoo",
  image: "https://images.prismic.io/ieeemuj/aENAfrh8WN-LVx4C_IMG_6284-VinayakJajoo.heic?auto=format,compress",
  role: "Treasurer",
  linkedin: "https://www.linkedin.com/in/vinayak-jajoo-414823250?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
  github: "",
  instagram: "https://www.instagram.com/vinayakjajoo?igsh=MWZ3NGFkNm83OTEwYg%3D%3D&utm_source=qr",
  note: "There’s a certain calmness about you that makes everything feel steady and in place 🥹 And then there’s your music, your melodies don’t just sound good, they stay. The way you play feels effortless yet so full of depth, like every note carries something meaningful. You’re that rare balance of logic and soul, where everything you do feels composed, thoughtful, and quietly beautiful 🫶🏻",
},
{
  name: "Bhavya Jaggi",
  image: "https://images.prismic.io/ieeemuj/aEM_tbh8WN-LVx3E_20250421_183325-BhavyaJaggi.jpg?auto=format,compress",
  role: "Human Resource Director",
  linkedin: "https://www.linkedin.com/in/bhavya-jaggi-20b768284?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  github: "https://github.com/BhavyaJaggi12",
  instagram: "https://www.instagram.com/bhav.ya_jaggi?igsh=MTQ0dGJjYWNjeXg0ag==",
  note: "You are truly one of the calmest and most comforting people to be around 🥹 There’s this softness in the way you handle everything- people, situations, even chaos that makes everything feel okay. So pyaare, so understanding, and so easy to talk to, you made everyone feel heard without even trying. A presence that grounds people and makes spaces feel lighter and kinder 🫶🏻",
},
{
  name: "Neil Gupta",
  image: "https://images.prismic.io/ieeemuj/aENAUbh8WN-LVx31_IMG_2745-NeilGupta.jpeg?auto=format,compress",
  role: "Technical Secretary",
  linkedin: "https://www.linkedin.com/in/neil-gupta-97a0242a1",
  github: "",
  instagram: "https://www.instagram.com/neilguptaa._?igsh=MWF0cXV5bHZ1Z3BsMg==",
  note: "You have this effortlessly cool, almost nonchalant energy that makes everything feel lighter ✨ Like no matter how complex things get, you handle it with a quiet “it’s chill” and somehow, it actually becomes chill. A total tech wizard, but never intimidating—just smooth, sharp, and lowkey iconic. There’s something very effortless about you, and that’s what makes you stand out the most. Cool without trying, and brilliant without showing off 🫶🏻",
},
];


export const CORE_MEMBERS: TeamMember[] = [
  {
  name: "Anmol Rawal",
  image: "/8.png",
  role: "Joint Head Media/Corporate Affair",
  note: "We will miss you",
},
  {
  name: "Aarush Dayal",
  image: "https://images.prismic.io/ieeemuj/aD2-Irh8WN-LVfO7_aarushdayal-ieeeweb-img-AarushDayal.jpeg?auto=format,compress",
  role: "Head of Programs",
  linkedin: "https://www.linkedin.com/in/aarush-dayal-790812215/",
  github: "",
  instagram: "https://instagram.com/aarushdayal",
    note: "Our Promo Head, known for his iconic “5 event ideas batao” 😭✨ Somehow, every conversation with you begins with that, and it’s become such a core memory for all of us. You always pushed us to think better and be more creative, even when it felt a little overwhelming at first. But that’s what made us grow. Your way of challenging us, mixed with your fun and light energy, made everything so memorable. Truly grateful for all the learnings and moments",
},
{
  name: "Tejas Bhadauria",
  image: "https://images.prismic.io/ieeemuj/aD2-_rh8WN-LVfP9_cropped-image-1--CrystalFire.png?auto=format,compress",
  role: "Joint Head of Programs",
  linkedin: "https://www.linkedin.com/in/tejas-bhadauria-513a78293?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  github: "https://github.com/CrystalFire1o8",
  instagram: "https://instagram.com/tejasbhadauriaa",
  note: "Bhaiya, you brought crystal clarity and a fiery spirit to everything we did. Thank you.",
},
{
  name: "Devang Sabarwal",
  image: "https://images.prismic.io/ieeemuj/aD2_s7h8WN-LVfQp_IMG_8475_Original-Devang.jpeg?auto=format,compress",
  role: "Senior Coordinator of Programs",
  linkedin: "https://www.linkedin.com/in/devang-sabbarwal-397563249?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
  github: "",
  instagram: "https://instagram.com/d4vang",
  note: "Bhaiya, your steady support made even the most complex days feel easy. You're a star.",
},
{
  name: "Saksham Jain",
  image: "https://images.prismic.io/ieeemuj/aD2__bh8WN-LVfRL_Image-SakshamJain.jpg?auto=format,compresss",
  role: "Senior Coordinator of Programs",
  linkedin: "http://www.linkedin.com/in/saksham-jain-x7",
  github: "",
  instagram: "https://instagram.com/_. saksham_jain",
  note: "Bhaiya, the energy you brought to every session was contagious. Keep that spark alive.",
},
{
  name: "Kavya Sharma",
  image: "https://images.prismic.io/ieeemuj/aD3AI7h8WN-LVfRa_1000077001-1--KavyaSharma.jpg?auto=format,compress",
  role: "Senior Coordinator of Programs",
  linkedin: "https://www.linkedin.com/in/kavya-sharma-479839335",
  github: "",
  instagram: "https://instagram.com/kavyaaa_9735 ",
  note: "Didi, your dedication was the silent strength behind our most successful days. Thank you.",
},
{
  name: "Arnav Pawar",
  image: "https://images.prismic.io/ieeemuj/aD3ASbh8WN-LVfRg_ArnavPawar-ArnavPawar.jpg?auto=format,compress",
  role: "Senior Coordinator of Programs",
  linkedin: "https://linkedin.com/in/arnav-pawar-080867349/",
  github: "",
  instagram: "https://instagram.com/arnav_pawarrr",
  note: "Bhaiya, you navigated every hurdle with such poise. You've taught us a lot about resilience.",
},
{
  name: "Aradhya Bansal",
  image: "https://images.prismic.io/ieeemuj/aD3Avbh8WN-LVfSG_ProfilePic-AradhyaBansal.jpg?auto=format,compress",
  role: "Senior Coordinator of Programs",
  linkedin: "https://www.linkedin.com/in/aradhyabansal2407",
  github: "",
  instagram: "https://instagram.com/aradhyabansal_24",
  note: "Bhaiya, your creative outlook and sweet nature made the team a better place for everyone.",
},
{
  name: "Sanidhya Jaiswal",
  image: "https://images.prismic.io/ieeemuj/aEM3hbh8WN-LVxrj_WhatsAppImage2025-06-05at14.39.33_3699181e.jpg?auto=format,compress",
  role: "Senior Coordinator of Programs",
  linkedin: "https://www.linkedin.com/in/sanidhya-jaiswal-033378325/",
  github: "https://github.com/Sanidhya-Jaiswal",
  instagram: "https://instagram.com/@saaaniiee",
  note: "You’ve always been that person everyone could rely on—super caring, always ready to help, and quietly making sure sab theek hai. And then randomly coming in with “tea dedo” like it’s your daily ritual 😭 somehow turning normal moments into the best ones. Always ready for a quick cards game no matter what the situation is—that energy is unmatched.",
},
{
  name: "Tamanna",
  image: "https://images.prismic.io/ieeemuj/aD3BY7h8WN-LVfS9_InShot_20250528_192147924-TamannaMalhotra.jpg?auto=format,compress",
  role: "Senior Coordinator of Programs",
  linkedin: "https://www.linkedin.com/in/tamannamalhotra24",
  github: "",
  instagram: "https://instagram.com/tamannamalhotra24 ",
  note: "Didi, your smile and cheerful spirit could lighten up even the longest meetings. We'll miss you.",
},
{
  name: "Hemank Kumar",
  image: "https://images.prismic.io/ieeemuj/aD3B_Lh8WN-LVfTR_pong-arty.jpeg?auto=format,compress",
  role: "Head of Technical Projects",
  linkedin: "https://www.linkedin.com/in/hemankkumar24/",
  github: "https://github.com/artyish",
  instagram: "https://instagram.com/hemankfr",
  note: "Bhaiya, you didn't just write code; you wrote a story of innovation and kindness. Thank you for leading us.",
},
{
  name: "Disha Chopra",
  image: "https://images.prismic.io/ieeemuj/aD3CJbh8WN-LVfTa_cropped-image-2--Disha.png?auto=format,compress",
  role: "Joint Head of Technical Projects",
  linkedin: "https://www.linkedin.com/in/disha-chopra-116244339",
  github: "",
  instagram: "https://instagram.com/_disha1210",
  note: "Didi, your ability to solve complex problems with a calm heart was inspiring to everyone around you.",
},
{
  name: "Tanmoy Mandal",
  image: "https://images.prismic.io/ieeemuj/aD3EmLh8WN-LVfVO_photo-Tanmay.jpg?auto=format,compresss",
  role: "Senior Coordinator of Technical Projects",
  linkedin: "https://www.linkedin.com/in/tanmoy-mandal-014a23326/",
  github: "https://github.com/Tanmayman0896",
  instagram: "https://instagram.com/notanmay._",
  note: "Some people teach, and some people make you feel like you can learn anything—you are the second kind ✨ Being around you was always so easy, so real, so full of those “maze aate hai” moments. Whether it was tech or just life, you carried everything with such calm confidence and humility. You never made things feel complicated—you made them feel possible. And that’s something we’ll always carry with us 🥹",
},
{
  name: "Shubh Somani",
  image: "https://images.prismic.io/ieeemuj/aD3DELh8WN-LVfUO_DA96186B-1752-4663-85A2-0A869CB9A5DC-ShubhSomani.jpeg?auto=format,compress",
  role: "Senior Coordinator of Technical Projects",
  linkedin: "https://www.linkedin.com/in/shubh-somani-aa4a49284",
  github: "https://github.com/ShubhxYT",
  instagram: "https://instagram.com/shubhsomani",
  note: "Bhaiya, you brought such positive energy and technical skill to the table. It's been an honor working with you.",
},
{
  name: "Siddharth Meena",
  image: "https://images.prismic.io/ieeemuj/aD3Dkbh8WN-LVfUm_1000093770-1--Siddarth.jpg?auto=format,compress",
  role: "Senior Coordinator of Technical Projects",
  linkedin: "https://www.linkedin.com/in/siddharth--meena",
  github: "https://github.com/SiddDevZ",
  instagram: "https://instagram.com/siddharthmz",
  note: "Bhaiya, your dedication and quiet strength helped us cross many finish lines. We won't forget you.",
},
{
  name: "Saksham Tyagi",
  image: "https://images.prismic.io/ieeemuj/aD3D-7h8WN-LVfUw_IMG_20250527_151837-SakshamTyagi.jpg?auto=format,compress",
  role: "Senior Coordinator of Technical Projects",
  linkedin: "https://www.linkedin.com/in/saksham-tyagi-369109288?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  github: "https://github.com/SakshamTyagi17",
  instagram: "https://instagram.com/tyagi_saksham_01",
  note: "Bhaiya, your hard work and technical insight were vital to our success. Thank you for your amazing spirit.",
},
{
  name: "Ayush Ranjan",
  image: "https://images.prismic.io/ieeemuj/aD3EIrh8WN-LVfU3_Ayush_Ranjan-AyushRanjan.jpg?auto=format,compress",
  role: "Senior Coordinator of Technical Projects",
  linkedin: "https://www.linkedin.com/in/ayush-ranjan-muj-cse/",
  github: "https://github.com/Ayush007-pro",
  instagram: "https://www.instagram.com/ayush_ranjan5429/",
  note: "Bhaiya, your presence was like a breath of fresh air in the lab. Your kindness and skill will be missed.",
},
{
  name: "Kushagra Kaushik",
  image: "https://images.prismic.io/ieeemuj/aEM2dLh8WN-LVxqH_WhatsAppImage2025-06-05at01.47.53_da5b4988.jpg?auto=format,compress",
  role: "Senior Coordinator of Technical Projects",
  linkedin: "https://www.linkedin.com/in/kushagrakaushik19",
  github: "",
  instagram: "https://instagram.com/ _uncaged._",
  note: "Bhaiya, thank you for pushing boundaries and bringing such a vibrant attitude to the core team.",
},
{
  name: "Abishri V K",
  image: "https://images.prismic.io/ieeemuj/aD3Harh8WN-LVfW4_20250528_143558-AbishriVK.jpg?auto=format,compress",
  role: "Senior Coordinator of Technical Projects",
  linkedin: "https://www.linkedin.com/in/abishri-v-k-199bb6333?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  github: "",
  instagram: "https://instagram.com/abishrii_kumar ",
  note: "Didi, your contributions were quiet but incredibly impactful. Thank you for your dedication.",
},
{
  name: "Anushka Singh",
  image: "https://images.prismic.io/ieeemuj/aD3Hprh8WN-LVfXD_IMG-20250528-WA0013-Anushka.jpg?auto=format,compress",
  role: "Senior Coordinator of Technical Projects",
  linkedin: "https://in.linkedin.com/in/anushka-singh-413098294",
  github: "https://github.com/anushkasinghxx",
  instagram: "https://instagram.com/nush.singh05",
  note: "Didi, you combined technical skill with a sweet helpfulness that made every project better.",
},
{
  name: "Abhijay Shrivastava",
  image: "https://images.prismic.io/ieeemuj/aD3IH7h8WN-LVfXW_Screenshot_20250528-131631-Abhijay.png?auto=format,compress",
  role: "Head of Graphic Design",
  linkedin: "https://www.linkedin.com/in/abhijay-shrivastava",
  github: "https://github.com/Abhijay0910",
  instagram: "https://instagram.com/Abhijay_0910",
  note: "Aap seriously bohut sweet ho—voice itni calm aur soft ki bas “hello” sunte hi mood better ho jata hai 😭 The way you explain things is just different, kabhi aisa feel hi nahi hota ki kuch samajh nahi aa raha—you make everything so easy without making anyone feel dumb. Honestly, aap sirf sweet nahi ho, you’re the kind of person people feel lucky to know. P.S. you look very hot while eating chicken",
},
{
  name: "Arindam Sharmaa",
  image: "https://images.prismic.io/ieeemuj/aEM4ILh8WN-LVxsP_IEEE3%5B1%5D.JPG?auto=format,compress",
  role: "Joint Head of Graphic Design",
  linkedin: "https://www.linkedin.com/in/arindam~sharma~5906",
  github: "",
  instagram: "https://instagram.com//arindamsharma05/",
  note: "Aap honestly sabse sweetest aur sabse innocent ho—there’s this genuine softness in the way you talk and the way you treat people that just feels rare. Everything about you is so simple and real, no pretence, no overthinking—bas pure intentions. 😭Honestly, aap jaise log bohot kam milte hain, and knowing you has been one of the nicest parts.",
},
{
  name: "Kartik Garg",
  image: "https://images.prismic.io/ieeemuj/aD3QSbh8WN-LVfeY_sqaurephoto-KartikGarg.jpg?auto=format,compress",
  role: "Senior Coordinator of Graphic Design",
  linkedin: "https://www.linkedin.com/in/kartikgarg123",
  github: "https://github.com/Kartik-Garg-13",
  instagram: "https://instagram.com/kartik_gargg",
  note: "Bhaiya, thank you for being the creative engine that kept our visuals fresh and vibrant.",
},
{
  name: "Abhinav Singh Negi",
  image: "https://images.prismic.io/ieeemuj/aD3Qe7h8WN-LVfep_avi3-1-%5B1%5D-aaravispro12.png?auto=format,compress",
  role: "Senior Coordinator of Graphic Design",
  linkedin: "https://www.linkedin.com/in/abhinav-singh-negi-28360a32a/",
  github: "https://github.com/AbhinvSinghNegi",
  instagram: "",
  note: "Bhaiya, your dedication to every pixel was a testament to your hard work. You'll be missed.",
},
{
  name: "Arjun Khanna",
  image: "https://images.prismic.io/ieeemuj/aD3Qubh8WN-LVfey_IMG_1473-arjunkhanna.jpeg?auto=format,compress",
  role: "Senior Coordinator of Graphic Design",
  linkedin: "https://www.linkedin.com/in/arjun-khanna8",
  github: "",
  instagram: "https://instagram.com/arjunnnkhanna",
  note: "Bhaiya, your presence added a special layer of creativity to the team. Thank you for your amazing designs.",
},
{
  name: "Aabha Rajpal ",
  image: "https://images.prismic.io/ieeemuj/aD3Q_7h8WN-LVfe7_Aabha_Rajpal-AabhaRajpal.jpg?auto=format,compress",
  role: "Head of Promotions",
  linkedin: "https://www.linkedin.com/in/aabha-rajpal-630b41300?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  github: "",
  instagram: "https://instagram.com/aabharajpal777",
  note: "You feel like a soft, beautiful moment that stays 🦋✨ Your love for butterflies mirrors your own presence—delicate, graceful, and quietly captivating. Everything about you feels so thoughtfully aesthetic, like a world where little details matter. You don’t just appreciate beauty—you carry it within you. Being around you feels calm, pretty, and a little magical 🥹💗",
},
{
  name: "Shreyas Kumar Singh",
  image: "https://images.prismic.io/ieeemuj/aD3RPbh8WN-LVffH_shreyaskrs-ShreyasKumarSingh.jpg?auto=format,compress",
  role: "Joint Head of Promotions",
  linkedin: "https://www.linkedin.com/in/shreyaskrs/",
  github: "https://github.com/shreyyaz",
  instagram: "https://instagram.com/shreyyaz",
  note: "You are the kind of person who turns spaces into memories and people into a family 🥹 There was always this warmth around you—like no matter how stressful things got, your presence made it all feel lighter. From your little “thoda aur promote karo guys” moments to your gentle “chill karo, ho jaayega,” you never let us feel alone in anything. You didn’t just include everyone, you noticed everyone—and that’s rare. A joyful, pookie soul who made this journey feel safe and happy 🫶🏻",
},
{
  name: "Samaira Agarwal",
  image: "https://images.prismic.io/ieeemuj/aD3RZrh8WN-LVffJ_IEEEpicture-SamairaAgarwal.jpeg?auto=format,compress",
  role: "Senior Coordinator of Promotions",
  linkedin: "https://www.linkedin.com/in/samaira-agarwal-3608b2247/",
  github: "",
  instagram: "https://instagram.com/samaira_201206",
  note: "Didi, your cheerful presence and dedication to promotions made every event a success. We'll miss you.",
},
{
  name: "Dev Kumar Raikwar",
  image: "https://images.prismic.io/ieeemuj/aD3Rjbh8WN-LVffL_94a7460e-ff3c-42fc-b6d1-603d1469d725-DevRaikwar.jpeg?auto=format,compress",
  role: "Senior Coordinator of Promotions",
  linkedin: "https://www.linkedin.com/in/dev-kumar-raikwar-x7/",
  github: "",
  instagram: "https://instagram.com/raikwarxdev@18",
  note: "Bhaiya, your hard work and positive attitude were key to making our team's reach truly global. Thank you.",
},
{
  name: "Aarav Shah",
  image: "https://images.prismic.io/ieeemuj/aD3RwLh8WN-LVffS_aaravshahIeee-AaravShah.jpeg?auto=format,compress",
  role: "Senior Coordinator of Promotions",
  linkedin: "https://www.linkedin.com/in/aarav-shah-741983349/",
  github: "",
  instagram: "https://instagram.com/aaravshah_1017",
  note: "Bhaiya, thank you for your commitment to the team and for always being ready with a creative promotion idea.",
},
{
  name: "Rashmi Singh",
  image: "https://images.prismic.io/ieeemuj/aD3SC7h8WN-LVffa_IMG_20250528_124026-RashmiSingh.jpg?auto=format,compress",
  role: "Senior Coordinator of Promotions",
  linkedin: "https://www.linkedin.com/in/rashmi-singh-6a743234a?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  github: "",
  instagram: "https://instagram.com/_.khayalipulao",
  note: "Didi, your dedication and support in promotions was truly inspiring. You've been a vital part of our journey.",
},
{
  name: "Sahanaa Vashishth",
  image: "https://images.prismic.io/ieeemuj/aD3SLrh8WN-LVffg_sana.2-sahanaav.jpg?auto=format,compress",
  role: "Senior Coordinator of Promotions",
  linkedin: "https://www.linkedin.com/in/sahanaa-vashishth-ba32a4332",
  github: "",
  instagram: "https://instagram.com/itzsahanaa",
  note: "Didi, thank you for bringing a touch of grace and hard work to every campaign we launched.",
},
{
  name: "Amiya Sharma",
  image: "https://images.prismic.io/ieeemuj/aD3Xubh8WN-LVfhz_IMG_3863-AmiyaSharma.jpg?auto=format,compress",
  role: "Senior Coordinator of Promotions",
  linkedin: "https://www.linkedin.com/in/amiya-sharma-75490933a?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
  github: "",
  instagram: "https://instagram.com/amiya_sharma13",
  note: "Didi, your spirit and dedication to promotions made a real difference. Thank you for being part of us.",
},
{
  name: "Sara Pansuriya",
  image: "https://images.prismic.io/ieeemuj/aD3YAbh8WN-LVfh5_IMG_0013_1_1080x1080-SaraPansuriya.jpeg?auto=format,compress",
  role: "Head of Editorial",
  linkedin: "https://www.linkedin.com/in/sara-pansuriya-936299338",
  github: "",
  instagram: "https://instagram.com/sarapansuriya",
  note: "You turned words into feelings and moments into memories ✨ As Editorial Head, you didn’t just write—you made people feel. And somehow, your personality is just as beautiful as your words. So warm, so adorable, so full of light—you’re truly our little munchkin with the biggest heart. You leave behind not just content, but emotions that will always stay 💌",
},
{
  name: "Shreya Daljeet",
  image: "https://images.prismic.io/ieeemuj/aD3Yebh8WN-LVfh7_IMG_7571-shreya.jpeg?auto=format,compress",
  role: "Joint Head of Editorial",
  linkedin: "https://www.linkedin.com/in/shreya-daljeet-4b7195231?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
  github: "",
  instagram: "https://instagram.com/shrxyeet",
  note: "You feel like comfort in its purest form 💗 The kind of presence that doesn’t need to be loud to be deeply felt. There’s something so gentle and genuine about you—like a quiet reassurance that everything will be okay. From your love for Milo to your endlessly kind heart, you’ve given us a softness we didn’t know we needed. You’re not just sweet—you’re unforgettable 🥹",
},
{
  name: "Brinda Kashyap",
  image: "https://images.prismic.io/ieeemuj/aD3YtLh8WN-LVfh__IMG_20250528_132203-BrindaKashyap.jpg?auto=format,compress",
  role: "Senior Coordinator of Editorial",
  linkedin: "https://www.linkedin.com/in/brinda-kashyap-b16933331/",
  github: "",
  instagram: "",
  note: "Didi, thank you for your commitment to excellence and for always polishing our stories to perfection.",
},
{
  name: "Divyanshi",
  image: "https://images.prismic.io/ieeemuj/aD_14rh8WN-LVkcP_IMG-20250527-WA0002-RaseshwariMishra.jpg?auto=format,compress",
  role: "Senior Coordinator of Editorial",
  linkedin: "https://www.linkedin.com/in/divyanshi-gusainwal-5b6b70350?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  github: "",
  instagram: "https://instagram.com/this_is_divyanshi___",
  note: "Didi, your hard work and creative spirit were a vital part of our team's voice. Thank you.",
},
{
  name: "Bhavika Yadav",
  image: "https://images.prismic.io/ieeemuj/aD3aTrh8WN-LVfi3_IMG_1301-BhavikaYadav.jpeg?auto=format,compress",
  role: "Senior Coordinator of Editorial",
  linkedin: "http://linkedin.com/in/bhavika-yadav-7b4b3a333",
  github: "",
  instagram: "https://instagram.com/bhavi_karao12",
  note: "Didi, thank you for your dedication and for always bringing a thoughtful perspective to our content.",
},
{
  name: "Dolly Srivastava",
  image: "https://images.prismic.io/ieeemuj/aD3a2rh8WN-LVfjA_wowkyaphotohai-DollySrivastava.jpg?auto=format,compress",
  role: "Head of Corporate Affairs",
  linkedin: "https://www.linkedin.com/in/dollysrivastava",
  github: "https://github.com/idkdolly",
  instagram: "https://instagram.com/dollysrivastava14 ",
  note: "You are the thread that quietly holds everything and everyone together 🫶🏻 Being Gen Sec was just your role, but being everyone’s favourite—that’s who you are. You made people feel seen, valued, and connected, without ever trying too hard. Because of you, this wasn’t just a chapter—it was a home. And that feeling is something we’ll never forget 🥹",
},
{
  name: "Charu Malik",
  image: "https://images.prismic.io/ieeemuj/aD3bG7h8WN-LVfjD_IMG_20250528_111333-CharuMalik.jpg?auto=format,compress",
  role: "Joint Head of Corporate Affairs",
  linkedin: "https://www.linkedin.com/in/charu-malik-56636733a",
  github: "",
  instagram: "https://instagram.com/_charuuuu._",
  note: "Didi, your dedication and sweet nature made every corporate interaction feel like a warm conversation.",
},
{
  name: "Disha Khemka",
  image: "https://images.prismic.io/ieeemuj/aD3bYbh8WN-LVfjL_ycl34430-DISHAKHEMKA.jpg?auto=format,compress",
  role: "Senior Coordinator of Corporate Affairs",
  linkedin: "https://www.linkedin.com/in/disha-khemka-868b3a35b/",
  github: "https://github.com/Disha-Khemka",
  instagram: "https://instagram.com/dishaa_khemka",
  note: "Didi, thank you for your commitment and for always representing our team with such integrity and grace.",
},
{
  name: "Saharsh Vaibhav Lal ",
  image: "https://images.prismic.io/ieeemuj/aD3eK7h8WN-LVfkw_IMG-20250527-WA0019_edited-2023AABAAD.jpeg?auto=format,compress",
  role: "Senior Coordinator of Corporate Affairs",
  linkedin: "https://www.linkedin.com/in/saharsh-vaibhav-lal-65061b317/",
  github: "",
  instagram: "https://instagram.com/saharsh_1_1_0_7",
  note: "Bhaiya, your hard work and positive spirit were key to our corporate success. We'll miss your presence.",
},
{
  name: "Ayush Tanwar",
  image: "https://images.prismic.io/ieeemuj/aD_ue7h8WN-LVkY0_IMG_20250109_032258763~2-AyushTanwar.jpg?auto=format,compress",
  role: "Head of Curations",
  linkedin: "https://www.linkedin.com/in/ayush-tanwar-x7/",
  github: "",
  instagram: "https://www.instagram.com/ayushtanwar_07/",
  note: "Bhaiya, your impeccable taste and vision for curations set a high standard for us all. Thank you for everything.",
},
{
  name: "Mehul Manohar Shah",
  image: "https://images.prismic.io/ieeemuj/aD_uubh8WN-LVkY6_IMG_6490-MehulManoharSah.JPG?auto=format,compress",
  role: "Joint Head of Curations",
  linkedin: "https://www.linkedin.com/in/mehul-manohar-sah-087a3835b",
  github: "",
  instagram: "https://instagram.com/mehul_manohar_sah",
  note: "Bhaiya, your dedication and sweet nature made the curation process a joyful journey for the entire team.",
},
{
  name: "Samarth Majumbdar",
  image: "https://images.prismic.io/ieeemuj/aD_u3Lh8WN-LVkY9_Samarth-SamarthMujumdar.jpg?auto=format,compress",
  role: "Senior Coordinator of Curations",
  linkedin: "https://www.linkedin.com/in/samarth-mujumdar-680468332",
  github: "https://github.com/SamarthMujumdar",
  instagram: "https://instagram.com/mujumdar_samarth",
  note: "Bhaiya, thank you for your meticulous work and for always ensuring that our team put its best foot forward.",
},
{
  name: "Aditya Chauhan",
  image: "https://images.prismic.io/ieeemuj/aEM2xLh8WN-LVxqf_WhatsAppImage2025-06-06at14.29.29_170f729b.jpg?auto=format,compress",
  role: "Senior Coordinator of Curations",
  linkedin: "https://www.linkedin.com/me?trk=p_mwlite_feed-secondary_nav",
  github: "https://github.com/adityaaachauhannn",
  instagram: "https://instagram.com/adityaa.c_",
  note: "Bhaiya, your hard work and technical insight were vital to our curation success. Thank you for your amazing spirit.",
},
{
  name: "Harshita Agarwal",
  image: "https://images.prismic.io/ieeemuj/aD_vQbh8WN-LVkZG_IMG_5088-Harshitaagarwal.JPG?auto=format,compress",
  role: "Senior Coordinator of Curations",
  linkedin: "https://www.linkedin.com/in/harshita-agarwal-a0578834b/",
  github: "https://github.com/harshita0102",
  instagram: "https://instagram.com/harshita.0102",
  note: "Didi, you combined curation skill with a sweet helpfulness that made every project better.",
},
{
  name: "Utkarsh Saxena",
  image: "https://images.prismic.io/ieeemuj/aD_veLh8WN-LVkZL_myphotoforieeewebsiteandinstapage-Utkarshsaxena.jpg?auto=format,compress",
  role: "Head of Logistics",
  linkedin: "https://www.linkedin.com/in/utkarsh-saxena-193163349/",
  github: "",
  instagram: "https://instagram.com/utkarsh_saxena.17",
  note: "Aap toh pure fun ho—full masti, full energy, and somehow making every moment lighter without even trying 😭 But at the same time, you’re also the one who notices the smallest things about people. Honestly, aap jaise log sirf good times nahi, real bonds bhi create karte hain—and that’s what makes you special.",
},
{
  name: "Keshav Anand",
  image: "https://images.prismic.io/ieeemuj/aD_vnLh8WN-LVkZP_96ad7182-9dd4-46bc-8a16-9f3a61cb9b04-KeshavAnand.jpeg?auto=format,compress",
  role: "Joint Head of Logistics",
  linkedin: "http://linkedin.com/in/keshav-anand-479712327",
  github: "",
  instagram: "https://instagram.com/keshav_anand_21",
  note: "Bhaiya, your calm handling of every logistical storm was truly impressive. Thank you for your amazing spirit.",
},
{
  name: "Samriddh Dwivedi",
  image: "https://images.prismic.io/ieeemuj/aD_v3bh8WN-LVkZV_IMG_20250529_185415-SamriddhDwivedi.jpg?auto=format,compress",
  role: "Head of Media",
  linkedin: "https://www.linkedin.com/in/samriddhdwivedi/",
  github: "",
  instagram: "https://www.instagram.com/samriddhdwivedi/",
  note: "Bhaiya, you captured our most beautiful moments and turned them into memories that will last forever. Thank you.",
},
{
  name: "Drishti Verma",
  image: "https://images.prismic.io/ieeemuj/aD_wC7h8WN-LVkZb_IMG-20250330-WA0347~2-drishtiverma.jpg?auto=format,compress",
  role: "Head of Social Media",
  linkedin: "https://www.linkedin.com/in/drishti-verma-240b2b302",
  github: "",
  instagram: "https://instagram.com/drishtivermav7",
  note: "You are the reason everything looked as beautiful as it felt 🌸✨ Your aesthetic sense didn’t just shape social media, it shaped how we experienced everything. There’s so much thought, detail, and love in what you do—and it shows. You didn’t just manage aesthetics, you became it 💖",
},
{
  name: "Arush Pradhan",
  image: "https://images.prismic.io/ieeemuj/aD3ByLh8WN-LVfTL_IMG-20250527-WA0009-ArushPradhan.jpg?auto=format,compress",
  role: "Joint Head of Social Media",
  linkedin: "https://www.linkedin.com/in/arush-pradhan-b2023b316?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  github: "",
  instagram: "https://instagram.com/cool_crusaderr",
  note: "You turned simple moments into something cinematic 🎸✨ Every time you played, it felt like time slowed down just a little. Your music, your vibe, your warmth—it all came together to create memories that feel so special now. You didn’t just play songs, you gave us feelings we’ll carry forever 🥹",
},
{
  name: "Arunika Jain",
  image: "https://images.prismic.io/ieeemuj/aD_wW7h8WN-LVkZn_IMG_6900-ArunikaJain.jpeg?auto=format,compress",
  role: "Senior Coordinator of Social Media",
  linkedin: "https://www.linkedin.com/in/arunika-jain22",
  github: "",
  instagram: "https://instagram.com/aruunikaaaaa",
  note: "Didi, your dedication and creative flair were vital to our social media success. You'll be missed.",
},
{
  name: "Ishika Taneja",
  image: "https://images.prismic.io/ieeemuj/aD_xH7h8WN-LVkZ7_4fb3d037-8257-4691-97c1-2d300677d0d8-IshikaTaneja.jpeg?auto=format,compress",
  role: "Senior Coordinator of Social Media",
  linkedin: "https://www.linkedin.com/in/ishika-taneja",
  github: "",
  instagram: "https://instagram.com/_ishika_taneja",
  note: "Didi, thank you for your hard work and for always bringing a fresh perspective to our social platforms.",
},
{
  name: "Janvi Singh",
  image: "https://images.prismic.io/ieeemuj/aD_xeLh8WN-LVkaA_ZeeResizer-JanviSingh.png?auto=format,compress",
  role: "Senior Coordinator of Social Media",
  linkedin: "https://www.linkedin.com/in/janvi-singh-55b680303?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  github: "",
  instagram: "https://instagram.com/_janvi.singhh",
  note: "Didi, your dedication and sweet helpfulness made the social media team a better place for everyone.",
},
{
  name: "Anushka Kalaskar",
  image: "https://images.prismic.io/ieeemuj/aD_xrrh8WN-LVkaI_IMG-20250528-WA0003-AnushkaKalaskar.jpg?auto=format,compress",
  role: "Senior Coordinator of Social Media",
  linkedin: "https://www.linkedin.com/in/anushka-kalaskar-714933327",
  github: "",
  instagram: "https://instagram.com/anushka.eh",
  note: "Didi, thank you for your tireless work and for always being ready to share our team's story with the world.",
},
{
  name: "Treshaa",
  image: "https://images.prismic.io/ieeemuj/aD_xy7h8WN-LVkaW_91971a82-9c1e-491e-80f6-db251cf5fe9c-TreshaaPathak.jpeg?auto=format,compress",
  role: "Senior Coordinator of Social Media",
  linkedin: "https://www.linkedin.com/in/treshaa-pathak",
  github: "https://github.com/dontcuttrees",
  instagram: "https://instagram.com/_.treshaa._",
  note: "Didi, your creative outlook and hard work were a vital part of our online presence. Thank you.",
},
{
  name: "Sindhuja Dubey",
  image: "https://images.prismic.io/ieeemuj/aD_x_7h8WN-LVkaf_c3134d90-11c9-45a8-91b9-80bcf7f88aa5-sindoooja.jpeg?auto=format,compress",
  role: "Head of Coverage",
  linkedin: "http://linkedin.com/in/sindhuja-d-b368a7256",
  github: "",
  instagram: "https://instagram.com/sindhuja.dubeyy",
  note: "Didi, you ensured that every story worth telling was covered with heart and precision. Thank you.",
},
{
  name: "Vaishak Yadav",
  image: "https://images.prismic.io/ieeemuj/aD_yKLh8WN-LVkaj_IMG_4762-VaishakYadav.jpeg?auto=format,compress",
  role: "Joint Head of Coverage",
  linkedin: "https://www.linkedin.com/in/vaishak-yadav-234481324?",
  github: "",
  instagram: "https://instagram.com/vaishakkkkk",
  note: "Bhaiya, your dedication to capturing the essence of our events has left us with a beautiful archive of memories.",
},
{
  name: "Harshvardhan Pathak",
  image: "https://images.prismic.io/ieeemuj/aD_yYrh8WN-LVkat_IMG_20250528_153136_796-HarshPat.jpg?auto=format,compress",
  role: "Senior Coordinator of Coverage",
  linkedin: "https://www.linkedin.com/in/harsh-pathak-v14",
  github: "",
  instagram: "https://instagram.com/Harsh.bhp",
  note: "Bhaiya, thank you for your commitment and for always being in the right place at the right time.",
},
{
  name: "Rakshit Dubey",
  image: "https://images.prismic.io/ieeemuj/aD_yoLh8WN-LVkay_IMG_0821-RakshitDubey.jpeg?auto=format,compress",
  role: "Head of Community",
  linkedin: "https://www.linkedin.com/in/rakshit-dubey-b9b799283?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
  github: "",
  instagram: "https://instagram.com/@rakkk_21",
  note: "Bhaiya, you built more than just a community; you built a family. Your heart is the soul of this team.",
},
{
  name: "Rahul Durgapal",
  image: "https://images.prismic.io/ieeemuj/aD_y37h8WN-LVka4_pic-RahulDurgapal.jpg?auto=format,compress",
  role: "Joint Head of Community",
  linkedin: "https://www.linkedin.com/in/rahuldurgapal555",
  github: "https://github.com/techie-rahul",
  instagram: "https://instagram.com/__rahul.555_",
  note: "Bhaiya, your dedication to bringing people together was truly inspiring. Thank you for your warmth and care.",
},
{
  name: "Sanskar Gupta",
  image: "https://images.prismic.io/ieeemuj/aD_zBLh8WN-LVka-_Sanskar_Gupta_Senior_Photo-SanskarGupta.jpg?auto=format,compress",
  role: "Senior Coordinator of Community",
  linkedin: "https://www.linkedin.com/in/sanskargupta2709/",
  github: "",
  instagram: "https://instagram.com/sanskargupta2709",
  note: "Bhaiya, thank you for your hard work and for always making sure that every member felt valued and heard.",
},
{
  name: "Anshuman Singh",
  image: "https://images.prismic.io/ieeemuj/aEM3B7h8WN-LVxqu_20250405_211338-AnshumanSingh.jpg?auto=format,compress",
  role: "Senior Coordinator of Community",
  linkedin: "https://www.linkedin.com/in/anshuman-singh-766088368/",
  github: "",
  instagram: "https://instagram.com/anshuman.singh070",
  note: "A guiding force who turned chaos into community and strangers into family. Your leadership, warmth, and quiet strength shaped us in ways words can’t fully capture—we’ll carry your impact forever.🥹",
},
{
  name: "Aarush Chandra",
  image: "https://images.prismic.io/ieeemuj/aD_zbLh8WN-LVkbL_What_Image_3e47uu3e47uu3e47-AarushChandra.png?auto=format,compress",
  role: "Senior Coordinator of Community",
  linkedin: "https://www.linkedin.com/in/aarush-chandra-4r724",
  github: "",
  instagram: "https://instagram.com/weird_kid_07",
  note: "You are the thread that quietly holds everything and everyone together 🫶🏻 Being Gen Sec was just your role, but being everyone’s favourite—that’s who you are. You made people feel seen, valued, and connected, without ever trying too hard. Because of you, this wasn’t just a chapter—it was a home. And that feeling is something we’ll never forget 🥹",
},
];
